### ISSUE TITLE
Dimension crash on spawn, subsequent chunk loading lag

### ISSUE THREAD

**Issue by aronson** [Gegy/tic-tacs#12]
I experienced an odd set of behaviors on commit 0629a7e0d43d9c3742a1a5c1b86bdac316f08b04

Upon installing Tic-Tacs:
* was last in a boat moving at a high velocity to a zero velocity in the nether using Tic-Tacs (stress testing)
* restarted server with Tic-Tacs, logged in to nether
* server crash, similar exception as issue #11 
* restart server, logged in
* no crash, boat is gone
* chunk loading was degraded, but still kind of working
* I fell through the empty chunk pictured and made my way back out of the void. Teleporting to a safe destination in the nether within my chunk sight distance timed out the server

Attached are logs and a screenshot of the behavior
![image](https://user-images.githubusercontent.com/1026348/92595178-f1ca1380-f271-11ea-8e5f-a531716eeaf7.png)
[2020-09-09-5.txt](http://ix.io/2wWo)
[2020-09-09-6.txt](http://ix.io/2wWk)
[crash-2020-09-09_07.43.43-server.txt](http://ix.io/2wWl)
[crash-2020-09-09_07.48.24-server.txt](http://ix.io/2wWm)
Also attached is a list of currently-installed mods
`fabric-api-0.20.1+build.401-1.16.jar  fabricmod_VoxelMap-1.10.10_for_1.16.2.jar  lithium-fabric-mc1.16.2-0.5.4.jar  modmenu-1.14.6+build.31.jar  phosphor-fabric-mc1.16.1-0.6.0+build.7.jar  servertick-1.2.jar  tic-tacs-0.1.0.jar`

I am happy to provide additional information as well as world data.

**Comment by Gegy** [comment]
This should be resolved in 0.1.1 :)
