### ISSUE TITLE
Hi. Is this good to have client-side, in multiplayer?

### ISSUE THREAD

**Issue by felix91gr** [Gegy/tic-tacs#13]
What the title says. I have a friend that I share a server with, who could use a couple extra fps.

Thanks in advance, and thank you for working on optimizing MC's stuff! This game is awesome but oh god the performance. Anywho. Thanks!!!

**Comment by Gegy** [comment]
Hi! Unfortunately, the main code this mod targets only really applies if there is a server running. It will definitely help in singleplayer where there's an integrated server running, but when just connected to a dedicated server, it shouldn't make much of a difference.

**Comment by felix91gr** [comment]
Thanks for the answer!

I see. Hmm 🤔
Do you think that it would help the server or the users if it were installed in the server itself? :)

**Comment by Gegy** [comment]
It would help the servers if installed on the server, but unfortunately if the client is lagging, there's nothing the server can do to help :(

**Comment by felix91gr** [comment]
Oh, okay. That makes sense :) 

Thanks again! 😊

**Comment by ghost** [comment]
This issue should now be closed,shouldn't it?

**Comment by felix91gr** [comment]
Sure! I have no more questions.

However, maybe it makes sense to leave the issue open so that people know about this? (I'm guessing this one is part of a FAQ)

Or maybe this information could appear in the readme 🤔

**Comment by jaskarth** [comment]
I'll make sure to put some more info in the wiki, thanks for your inquiries :+1:
