### ISSUE TITLE
1.12.

### ISSUE THREAD

**Issue by MagmaSlime123** [Gegy/tic-tacs#19]

**Comment by MagmaSlime123** [comment]
Why.

**Comment by Gegy** [comment]
The biggest reason is that this mod doesn't really make sense at all in 1.12; "TACS" (the code which this mod reimplements) was only added in 1.14.

**Comment by MagmaSlime123** [comment]
1.12 could be possible but apparently you're not wanting to.

**Comment by Gegy** [comment]
Yes.
