### ISSUE TITLE
Game crashing when loading a singleplayer world

### ISSUE THREAD

**Issue by ElliotS2007** [Gegy/tic-tacs#25]
[latest.log](https://github.com/Gegy/tic-tacs/files/5703425/latest.log)

Game crashes when using Sodium, Lithium, Phosphor and starlight. Dosen't happen when not using tic-TACS

Latest commit on all of theese mods and using java 15

**Comment by Gegy** [comment]
The issue here is fabriczero, which somehow causes Unsafe to not exist. (See #9)

Aside from that, phosphor and starlight are not compatible and it is probably not a good idea to use them together. :P
