### ISSUE TITLE
Incompatible with Lithium on server

### ISSUE THREAD

**Issue by emortaldev** [Gegy/tic-tacs#27]
(is tic-tacs supposed to be used on a server?)

`Method overwrite conflict for method_12121 in lithium.mixins.json:world.chunk_access.ServerChunkManagerMixin, previously written by net.gegy1000.tictacs.mixin.unblocking.ServerChunkManagerMixin. Skipping method.`

(edit)
no idea what i was doing, it's working fine

**Comment by U5B** [comment]
Seems it only happens with the first startup, after running my start script again my server loads up fine.

**Comment by Gegy** [comment]
I've seen this before too- it seems that Lithium doesn't respect mixin management configs from other mods on first startup, but I haven't looked into it at all.
