### ISSUE TITLE
server crashes when using the chunk pregeneration mod

### ISSUE THREAD

**Issue by Titaniumtown** [Gegy/tic-tacs#3]
I was pregenerating chunks: /pregen start 10
it got stuck at 41 chunks generated, then crashes

I was also using phosphor and lithium, I don't know if that matters though.

here's the log:
https://pastebin.com/c9DQBDis

**Comment by Valleriite** [comment]
maybe try without lithium,
maybe,it is the one causing issues.

**Comment by ghost** [comment]
never mind my previous comment,didn't read the issue fully, sorry

**Comment by Gegy** [comment]
This should be fixed now- let me know if this is still causing issues
