### ISSUE TITLE
Not compatible with the latest Starlight

### ISSUE THREAD

**Issue by QPCrummer** [Gegy/tic-tacs#30]
It is incompatible with starlight 0.0.2 RC2. I am using Tic-Tacs 0.1.3 .

![](https://user-images.githubusercontent.com/66036033/103096871-65025600-45d3-11eb-8396-3f9c3ea474f5.JPG)

**Comment by Gegy** [comment]
This should be resolved in https://github.com/Gegy/tic-tacs/commit/41231d8254278f40b3ce671936cce2f1e4aff9fa
