### ISSUE TITLE
Game gives up at render distances like 128

### ISSUE THREAD

**Issue by nonetrix** [Gegy/tic-tacs#38]
if you set the render distance to 128 the game only loads  a few chunks then stops and mobs in the unloaded chunks act weird and the CPU doesn't get stressed at all even though I changed the max threads

**Comment by nonetrix** [comment]
is listed in read me

**Comment by Obydux** [comment]
127 works tho

**Comment by nonetrix** [comment]
I wonder what cause this I don't know much about game dev or java just crappy Python and C++ if I feel cute

**Comment by Obydux** [comment]
Basically the view distance uses a signed 8 bit integer which means it can be -128 to 127

**Comment by Gegy** [comment]
This would be resolved along with #21
