### ISSUE TITLE
will there be updates?

### ISSUE THREAD

**Issue by ghost** [Gegy/tic-tacs#44]

**Comment by K0-RR** [comment]
![Screenshot from 2021-06-21 17-19-59](https://user-images.githubusercontent.com/43277609/122786798-f9b0ec80-d2b4-11eb-970f-96e190042c31.png)

**Comment by Gegy** [comment]
I may resume work on this in the future, but it’s not currently definitively planned at all. Sorry about that!

**Comment by Felix14-v2** [comment]
╯︿╰
So, the appearance of this mod in 1.17 will not be soon?

**Comment by K0-RR** [comment]
You can use C2ME mod. It's a similar concept afaik.

**Comment by Felix14-v2** [comment]
Yes, I know about it. But it works worse to me...
