### ISSUE TITLE
Will there be an update ?

### ISSUE THREAD

**Issue by ghost** [Gegy/tic-tacs#45]
I like the idea of being able to play more than 32 chunks on drawing along with sodium
But I found some bugs, for example, an unloaded part of the world that does not load, it only helps to re-enter the world

**Comment by CodeF53** [comment]
![image](https://user-images.githubusercontent.com/37855219/124524490-7618f480-ddb8-11eb-9195-8cb424bcb321.png)
This mod is not being updated right now

C2ME is very similar to this mod
https://github.com/ishlandbukkit/C2ME-fabric/

Bobby is another alternative, but helps render further distances by caching
https://github.com/Johni0702/bobby/

Hopefully Bobby and C2ME will work together sometime, creating a near-perfect solution.
