### ISSUE TITLE
Crashing with fabric-carpet-1.16.2-1.4.8+v200811

### ISSUE THREAD

**Issue by PhantomG27249** [Gegy/tic-tacs#5]
Attempting to boot a server with carpet installed along with tic-tacs will cause the server to crash on start up.

**Comment by Gegy** [comment]
Can you share the crash report? :)

**Comment by PhantomG27249** [comment]
I would if I could but it crashes the server before it gets a chance to generate anything, its a start the server then the program immediately exits crash.

**Comment by DrexHD** [comment]
It's caused by mixin conflicts: https://paste.lucko.me/3AcekXIuR7

**Comment by Gegy** [comment]
Looks like that Mixin just got removed: https://github.com/gnembon/fabric-carpet/commit/dedd6e3c8f64c28d23b45676c249d9fde19bad22
