### ISSUE TITLE
Crashes with FabricZero installed

### ISSUE THREAD

**Issue by PhantomG27249** [Gegy/tic-tacs#9]
On world load game will crash if fabric zero is installed
[crash-2020-09-05_12.58.30-server.txt](https://github.com/gegy1000/tic-tacs/files/5178552/crash-2020-09-05_12.58.30-server.txt)

**Comment by Gegy** [comment]
Are you sure this is caused by FabricZero? It's possible that it could be due to Java version

**Comment by Gegy** [comment]
Looks like FabricZero issue on >J8 https://github.com/Fox2Code/FabricZero/issues/1

**Comment by PhantomG27249** [comment]
its not because fabriczero doesn't work with java 9+ now as I am using it on java 11 rn. Its strange I only get these crash using it with tic-tacs wierd.

**Comment by Gegy** [comment]
Maybe try with the arguments that were recommended in that issue: `--add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/jdk.internal.vm.annotation=ALL-UNNAMED`
Regardless, this is definitely not a tic-tacs issue :P

**Comment by PhantomG27249** [comment]
kk got it lets give that a test.

**Comment by PhantomG27249** [comment]
Unfortunately it looks like I was already using them. Guess it might be some weirdness do to fabzeros end that only gets triggered by tic-tacs or some wierd interaction.
